xstr = str("Hello World")
print(xstr)
xint = int(20)
print(xint)
xfloat = float(20.5)
print(xfloat)
xcomplex = complex(1j)
print(xcomplex)
xlist = list(("apple", "banana", "cherry"))
print(xlist)
xtuple = tuple(("apple", "banana", "cherry"))
print(xtuple)
xrange = range(6)
print(xrange)
xict = dict(name="John", age=36)
print(xict)
xset = set(("apple", "banana", "cherry"))
print(xset)
xfrozenset = frozenset(("apple", "banana", "cherry"))
print(xfrozenset)
xbool = bool(5)
print(xbool)
xytes = bytes(5)
print(xytes)
xbytearray = bytearray(5)
print(xbytearray)
xmemoryview = memoryview(bytes(5))
print(xmemoryview)